# Copyright by Shlomi Fish, 2018 under the Expat licence
# https://opensource.org/licenses/mit-license.php
all: euler-75

euler-75: euler_75_v1.c
	gcc -std=gnu99 -O2 -o $@ $< -lm

clean:
	rm -f euler-75
